from __future__ import annotations

from typing import Any


def build_tools() -> list[dict[str, Any]]:
    """Return base MCP tool definitions shared by stdio bridge and HTTP daemon.

    Notes:
    - This returns a fresh list each call (safe to mutate).
    - Shared schema extensions (read identity + write contract ack) are applied
      by the transport layer via aicos_kernel.mcp_tool_schema.
    """

    return [{'name': 'aicos_get_startup_bundle',
             'description': 'Return a compact AICOS startup bundle for one actor and project scope.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string',
                                                      'description': 'Actor family/role, for example A1 or A2-Core-C.'},
                                            'scope': {'type': 'string',
                                                      'description': 'Project scope, for example '
                                                                     'projects/sample-project.'}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_get_handoff_current',
             'description': 'Return the H1 current handoff bundle for one project scope.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'}, 'scope': {'type': 'string'}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_get_packet_index',
             'description': 'Return compact task packet index for one actor and project scope.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'}, 'scope': {'type': 'string'}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_get_task_packet',
             'description': 'Return one selected task packet bundle.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'},
                                            'scope': {'type': 'string'},
                                            'packet_id': {'type': 'string'}},
                             'required': ['actor', 'scope', 'packet_id']}},
            {'name': 'aicos_get_status_items',
             'description': 'Return structured project status items with optional filters.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'},
                                            'scope': {'type': 'string'},
                                            'status_filter': {'type': 'array', 'items': {'type': 'string'}},
                                            'item_type_filter': {'type': 'array', 'items': {'type': 'string'}},
                                            'status_work_lane_filter': {'type': 'string',
                                                                        'description': 'Optional filter for status item '
                                                                                       'work_lane. Do not use read identity '
                                                                                       'work_lane as a filter.'},
                                            'status_agent_family_filter': {'type': 'string',
                                                                           'description': 'Optional filter for status item '
                                                                                          'agent_family. Do not use read identity '
                                                                                          'agent_family as a filter.'},
                                            'max_results': {'type': 'integer'},
                                            'include_stale': {'type': 'boolean',
                                                              'description': 'Include stale/closed items. Defaults to false.'}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_get_workstream_index',
             'description': 'Return project-declared workstream routing/context map when present.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'},
                                            'scope': {'type': 'string'},
                                            'include_candidate': {'type': 'boolean'},
                                            'status_filter': {'type': 'array', 'items': {'type': 'string'}}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_get_context_registry',
             'description': 'Return metadata registry entries for project/shared context sources.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'},
                                            'scope': {'type': 'string'},
                                            'max_results': {'type': 'integer'},
                                            'project_role': {'type': 'string'}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_get_project_registry',
             'description': 'Return the shared AICOS project registry and parsed project entries.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'}, 'scope': {'type': 'string'}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_get_feedback_digest',
             'description': 'Return recent structured feedback signals for a project.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'},
                                            'scope': {'type': 'string'},
                                            'max_results': {'type': 'integer'}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_get_project_health',
             'description': 'Return a compact operational/control-plane health view for a project.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'}, 'scope': {'type': 'string'}},
                             'required': ['actor', 'scope']}},
            {'name': 'aicos_query_project_context',
             'description': 'Run a scoped search over AICOS hot context for the given project scope.',
             'inputSchema': {'type': 'object',
                             'properties': {'actor': {'type': 'string'},
                                            'scope': {'type': 'string'},
                                            'query': {'type': 'string'},
                                            'project_role': {'type': 'string'},
                                            'context_kinds': {'type': 'array', 'items': {'type': 'string'}},
                                            'include_stale': {'type': 'boolean'},
                                            'max_results': {'type': 'integer'},
                                            'work_branch': {'type': 'string'},
                                            'worktree_path': {'type': 'string'}},
                             'required': ['actor', 'scope', 'query']}},
            {'name': 'aicos_record_checkpoint',
             'description': 'Record a checkpoint to AICOS evidence folder with stable metadata.',
             'inputSchema': {'type': 'object',
                             'properties': {'scope': {'type': 'string'},
                                            'actor_role': {'type': 'string',
                                                           'description': 'Role lane doing the work, for example A1, A2-Core-C, or A2-Core-R.'},
                                            'agent_family': {'type': 'string',
                                                             'description': 'Agent/client family, for example codex, claude-code, gemini-antigravity, or openclaw.'},
                                            'agent_instance_id': {'type': 'string',
                                                                  'description': 'Unique session/instance id for this agent run.'},
                                            'agent_display_name': {'type': 'string'},
                                            'work_type': {'type': 'string',
                                                          'enum': ['code',
                                                                   'content',
                                                                   'design',
                                                                   'research',
                                                                   'ops',
                                                                   'review',
                                                                   'planning',
                                                                   'data',
                                                                   'mixed',
                                                                   'orientation']},
                                            'work_lane': {'type': 'string'},
                                            'coordination_status': {'type': 'string',
                                                                    'enum': ['active', 'paused', 'blocked', 'handoff_ready', 'completed']},
                                            'artifact_scope': {'type': 'string'},
                                            'work_branch': {'type': 'string'},
                                            'worktree_path': {'type': 'string'},
                                            'execution_context': {'type': 'string'},
                                            'actor_family': {'type': 'string'},
                                            'logical_role': {'type': 'string'},
                                            'work_context': {'type': 'string'},
                                            'checkpoint_type': {'type': 'string',
                                                                'enum': ['design_review',
                                                                         'implementation_note',
                                                                         'migration_note',
                                                                         'decision_note',
                                                                         'research_note',
                                                                         'runtime_note',
                                                                         'eval_result',
                                                                         'test_result',
                                                                         'other']},
                                            'status': {'type': 'string', 'enum': ['active', 'completed', 'blocked', 'paused']},
                                            'summary': {'type': 'string'},
                                            'notes': {'type': 'string'},
                                            'handoff_ref': {'type': 'string'},
                                            'client_request_id': {'type': 'string'},
                                            'startup_bundle_ref': {'type': 'string'},
                                            'packet_ref': {'type': 'string'},
                                            'scope_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'session_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'artifact_refs': {'type': 'array', 'items': {'type': 'string'}}},
                             'required': ['scope',
                                          'actor_role',
                                          'agent_family',
                                          'agent_instance_id',
                                          'work_type',
                                          'work_lane',
                                          'checkpoint_type',
                                          'status',
                                          'summary']}},
            {'name': 'aicos_write_task_update',
             'description': 'Write a task-state update entry (append) for the given project scope.',
             'inputSchema': {'type': 'object',
                             'properties': {'scope': {'type': 'string'},
                                            'actor_role': {'type': 'string',
                                                           'description': 'Role lane doing the work, for example A1, A2-Core-C, or A2-Core-R.'},
                                            'agent_family': {'type': 'string',
                                                             'description': 'Agent/client family, for example codex, claude-code, gemini-antigravity, or openclaw.'},
                                            'agent_instance_id': {'type': 'string',
                                                                  'description': 'Unique session/instance id for this agent run.'},
                                            'agent_display_name': {'type': 'string'},
                                            'work_type': {'type': 'string',
                                                          'enum': ['code',
                                                                   'content',
                                                                   'design',
                                                                   'research',
                                                                   'ops',
                                                                   'review',
                                                                   'planning',
                                                                   'data',
                                                                   'mixed',
                                                                   'orientation']},
                                            'work_lane': {'type': 'string'},
                                            'coordination_status': {'type': 'string',
                                                                    'enum': ['active', 'paused', 'blocked', 'handoff_ready', 'completed']},
                                            'artifact_scope': {'type': 'string'},
                                            'work_branch': {'type': 'string'},
                                            'worktree_path': {'type': 'string'},
                                            'execution_context': {'type': 'string'},
                                            'actor_family': {'type': 'string'},
                                            'logical_role': {'type': 'string'},
                                            'work_context': {'type': 'string'},
                                            'task_ref': {'type': 'string'},
                                            'task_status': {'type': 'string', 'enum': ['active', 'paused', 'blocked', 'completed']},
                                            'what_is_done': {'type': 'string'},
                                            'next_step': {'type': 'string'},
                                            'what_is_blocked': {'type': 'string'},
                                            'handoff_ref': {'type': 'string'},
                                            'client_request_id': {'type': 'string'},
                                            'startup_bundle_ref': {'type': 'string'},
                                            'packet_ref': {'type': 'string'},
                                            'scope_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'session_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'artifact_refs': {'type': 'array', 'items': {'type': 'string'}}},
                             'required': ['scope',
                                          'actor_role',
                                          'agent_family',
                                          'agent_instance_id',
                                          'work_type',
                                          'work_lane',
                                          'task_ref',
                                          'task_status',
                                          'what_is_done']}},
            {'name': 'aicos_write_handoff_update',
             'description': 'Write a handoff update (append) into working/handoff/current.md for a project scope.',
             'inputSchema': {'type': 'object',
                             'properties': {'scope': {'type': 'string'},
                                            'actor_role': {'type': 'string',
                                                           'description': 'Role lane doing the work, for example A1, A2-Core-C, or A2-Core-R.'},
                                            'agent_family': {'type': 'string',
                                                             'description': 'Agent/client family, for example codex, claude-code, gemini-antigravity, or openclaw.'},
                                            'agent_instance_id': {'type': 'string',
                                                                  'description': 'Unique session/instance id for this agent run.'},
                                            'agent_display_name': {'type': 'string'},
                                            'work_type': {'type': 'string',
                                                          'enum': ['code',
                                                                   'content',
                                                                   'design',
                                                                   'research',
                                                                   'ops',
                                                                   'review',
                                                                   'planning',
                                                                   'data',
                                                                   'mixed',
                                                                   'orientation']},
                                            'work_lane': {'type': 'string'},
                                            'coordination_status': {'type': 'string',
                                                                    'enum': ['active', 'paused', 'blocked', 'handoff_ready', 'completed']},
                                            'artifact_scope': {'type': 'string'},
                                            'work_branch': {'type': 'string'},
                                            'worktree_path': {'type': 'string'},
                                            'execution_context': {'type': 'string'},
                                            'actor_family': {'type': 'string'},
                                            'logical_role': {'type': 'string'},
                                            'work_context': {'type': 'string'},
                                            'status': {'type': 'string', 'enum': ['active', 'completed', 'blocked', 'paused']},
                                            'summary': {'type': 'string'},
                                            'notes': {'type': 'string'},
                                            'next_step': {'type': 'string'},
                                            'client_request_id': {'type': 'string'},
                                            'startup_bundle_ref': {'type': 'string'},
                                            'packet_ref': {'type': 'string'},
                                            'scope_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'session_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'artifact_refs': {'type': 'array', 'items': {'type': 'string'}}},
                             'required': ['scope',
                                          'actor_role',
                                          'agent_family',
                                          'agent_instance_id',
                                          'work_type',
                                          'work_lane',
                                          'next_step',
                                          'status',
                                          'summary']}},
            {'name': 'aicos_update_status_item',
             'description': 'Write or update one status item markdown file in working/status-items.',
             'inputSchema': {'type': 'object',
                             'properties': {'scope': {'type': 'string'},
                                            'actor_role': {'type': 'string',
                                                           'description': 'Role lane doing the work, for example A1, A2-Core-C, or A2-Core-R.'},
                                            'agent_family': {'type': 'string',
                                                             'description': 'Agent/client family, for example codex, claude-code, gemini-antigravity, or openclaw.'},
                                            'agent_instance_id': {'type': 'string',
                                                                  'description': 'Unique session/instance id for this agent run.'},
                                            'agent_display_name': {'type': 'string'},
                                            'work_type': {'type': 'string',
                                                          'enum': ['code',
                                                                   'content',
                                                                   'design',
                                                                   'research',
                                                                   'ops',
                                                                   'review',
                                                                   'planning',
                                                                   'data',
                                                                   'mixed',
                                                                   'orientation']},
                                            'work_lane': {'type': 'string'},
                                            'coordination_status': {'type': 'string',
                                                                    'enum': ['active', 'paused', 'blocked', 'handoff_ready', 'completed']},
                                            'artifact_scope': {'type': 'string'},
                                            'work_branch': {'type': 'string'},
                                            'worktree_path': {'type': 'string'},
                                            'execution_context': {'type': 'string'},
                                            'actor_family': {'type': 'string'},
                                            'logical_role': {'type': 'string'},
                                            'work_context': {'type': 'string'},
                                            'item_id': {'type': 'string'},
                                            'item_type': {'type': 'string',
                                                          'enum': ['open_item', 'tech_debt', 'open_question', 'decision_followup', 'defect']},
                                            'item_status': {'type': 'string',
                                                            'enum': ['open', 'active', 'paused', 'blocked', 'resolved', 'stale', 'closed']},
                                            'title': {'type': 'string'},
                                            'summary': {'type': 'string'},
                                            'reason': {'type': 'string'},
                                            'next_step': {'type': 'string'},
                                            'source_ref': {'type': 'string',
                                                           'description': 'Repo-relative source path only. Use scope_refs for projects/... and session_refs for agent/thread ids.'},
                                            'handoff_ref': {'type': 'string'},
                                            'client_request_id': {'type': 'string'},
                                            'startup_bundle_ref': {'type': 'string'},
                                            'packet_ref': {'type': 'string'},
                                            'scope_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'session_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'artifact_refs': {'type': 'array', 'items': {'type': 'string'}}},
                             'required': ['scope',
                                          'actor_role',
                                          'agent_family',
                                          'agent_instance_id',
                                          'work_type',
                                          'work_lane',
                                          'item_id',
                                          'item_type',
                                          'item_status',
                                          'title',
                                          'summary']}},
            {'name': 'aicos_register_artifact_ref',
             'description': 'Register a compact artifact reference without copying artifact body into AICOS.',
             'inputSchema': {'type': 'object',
                             'properties': {'scope': {'type': 'string'},
                                            'actor_role': {'type': 'string',
                                                           'description': 'Role lane doing the work, for example A1, A2-Core-C, or A2-Core-R.'},
                                            'agent_family': {'type': 'string',
                                                             'description': 'Agent/client family, for example codex, claude-code, gemini-antigravity, or openclaw.'},
                                            'agent_instance_id': {'type': 'string',
                                                                  'description': 'Unique session/instance id for this agent run.'},
                                            'agent_display_name': {'type': 'string'},
                                            'work_type': {'type': 'string',
                                                          'enum': ['code',
                                                                   'content',
                                                                   'design',
                                                                   'research',
                                                                   'ops',
                                                                   'review',
                                                                   'planning',
                                                                   'data',
                                                                   'mixed',
                                                                   'orientation']},
                                            'work_lane': {'type': 'string'},
                                            'coordination_status': {'type': 'string',
                                                                    'enum': ['active', 'paused', 'blocked', 'handoff_ready', 'completed']},
                                            'artifact_scope': {'type': 'string'},
                                            'work_branch': {'type': 'string'},
                                            'worktree_path': {'type': 'string'},
                                            'execution_context': {'type': 'string'},
                                            'actor_family': {'type': 'string'},
                                            'logical_role': {'type': 'string'},
                                            'work_context': {'type': 'string'},
                                            'artifact_kind': {'type': 'string',
                                                              'enum': ['note',
                                                                       'report',
                                                                       'diff',
                                                                       'output',
                                                                       'analysis',
                                                                       'contract_check',
                                                                       'dataset',
                                                                       'design',
                                                                       'content',
                                                                       'other']},
                                            'title': {'type': 'string'},
                                            'artifact_ref': {'type': 'string'},
                                            'summary': {'type': 'string'},
                                            'source_ref': {'type': 'string',
                                                           'description': 'Repo-relative source path only. Use scope_refs for projects/... and session_refs for agent/thread ids.'},
                                            'client_request_id': {'type': 'string'},
                                            'startup_bundle_ref': {'type': 'string'},
                                            'packet_ref': {'type': 'string'},
                                            'handoff_ref': {'type': 'string'},
                                            'scope_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'session_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'artifact_refs': {'type': 'array', 'items': {'type': 'string'}}},
                             'required': ['scope',
                                          'actor_role',
                                          'agent_family',
                                          'agent_instance_id',
                                          'work_type',
                                          'work_lane',
                                          'artifact_kind',
                                          'title',
                                          'artifact_ref',
                                          'summary']}},
            {'name': 'aicos_record_feedback',
             'description': 'Record a structured AICOS/project context-serving feedback signal.',
             'inputSchema': {'type': 'object',
                             'properties': {'scope': {'type': 'string'},
                                            'actor_role': {'type': 'string'},
                                            'agent_family': {'type': 'string'},
                                            'agent_instance_id': {'type': 'string'},
                                            'agent_display_name': {'type': 'string'},
                                            'work_type': {'type': 'string',
                                                          'enum': ['code',
                                                                   'content',
                                                                   'design',
                                                                   'research',
                                                                   'ops',
                                                                   'review',
                                                                   'planning',
                                                                   'data',
                                                                   'mixed',
                                                                   'orientation']},
                                            'work_lane': {'type': 'string'},
                                            'coordination_status': {'type': 'string',
                                                                    'enum': ['active', 'paused', 'blocked', 'handoff_ready', 'completed']},
                                            'artifact_scope': {'type': 'string'},
                                            'work_branch': {'type': 'string'},
                                            'worktree_path': {'type': 'string'},
                                            'execution_context': {'type': 'string'},
                                            'actor_family': {'type': 'string'},
                                            'logical_role': {'type': 'string'},
                                            'work_context': {'type': 'string'},
                                            'feedback_type': {'type': 'string',
                                                              'enum': ['no_issue',
                                                                       'query_failed',
                                                                       'stale_result',
                                                                       'context_missing',
                                                                       'context_overload',
                                                                       'rule_confusing',
                                                                       'tool_missing',
                                                                       'tool_shape_confusing',
                                                                       'tool_too_heavy',
                                                                       'bootstrap_confusing',
                                                                       'write_schema_confusing',
                                                                       'interop_problem',
                                                                       'packet_missing_ref',
                                                                       'handoff_too_long',
                                                                       'work_state_missing',
                                                                       'work_state_ambiguous',
                                                                       'work_state_stale',
                                                                       'work_state_conflict',
                                                                       'ownership_unclear',
                                                                       'role_context_wrong',
                                                                       'routing_confusing',
                                                                       'other']},
                                            'severity': {'type': 'string',
                                                         'enum': ['low', 'medium', 'high', 'critical']},
                                            'title': {'type': 'string'},
                                            'summary': {'type': 'string'},
                                            'observed_in': {'type': 'string'},
                                            'recommendation': {'type': 'string'},
                                            'source_ref': {'type': 'string',
                                                           'description': 'Repo-relative source path only. Use scope_refs for projects/... and session_refs for agent/thread ids.'},
                                            'client_request_id': {'type': 'string'},
                                            'startup_bundle_ref': {'type': 'string'},
                                            'packet_ref': {'type': 'string'},
                                            'handoff_ref': {'type': 'string'},
                                            'scope_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'session_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'artifact_refs': {'type': 'array', 'items': {'type': 'string'}}},
                             'required': ['scope',
                                          'actor_role',
                                          'agent_family',
                                          'agent_instance_id',
                                          'work_type',
                                          'work_lane',
                                          'feedback_type',
                                          'severity',
                                          'title',
                                          'summary']}},
            {'name': 'aicos_propose_project',
             'description': 'Propose a new AICOS project scope when the project does not exist yet. Records an intake proposal only; it does not create the project.',
             'inputSchema': {'type': 'object',
                             'properties': {'scope': {'type': 'string',
                                                       'description': 'Requested project scope, for example projects/new-project-id. The scope must not already exist.'},
                                            'proposed_project_id': {'type': 'string',
                                                                    'description': 'Stable project id matching scope projects/<proposed_project_id>.'},
                                            'actor_role': {'type': 'string'},
                                            'agent_family': {'type': 'string'},
                                            'agent_instance_id': {'type': 'string'},
                                            'agent_display_name': {'type': 'string'},
                                            'work_type': {'type': 'string',
                                                          'enum': ['code',
                                                                   'content',
                                                                   'design',
                                                                   'research',
                                                                   'ops',
                                                                   'review',
                                                                   'planning',
                                                                   'data',
                                                                   'mixed',
                                                                   'orientation']},
                                            'work_lane': {'type': 'string'},
                                            'coordination_status': {'type': 'string',
                                                                    'enum': ['active', 'paused', 'blocked', 'handoff_ready', 'completed']},
                                            'artifact_scope': {'type': 'string'},
                                            'work_branch': {'type': 'string'},
                                            'worktree_path': {'type': 'string'},
                                            'execution_context': {'type': 'string'},
                                            'actor_family': {'type': 'string'},
                                            'logical_role': {'type': 'string'},
                                            'work_context': {'type': 'string'},
                                            'title': {'type': 'string'},
                                            'summary': {'type': 'string'},
                                            'reason': {'type': 'string'},
                                            'initial_goal': {'type': 'string'},
                                            'suggested_owner': {'type': 'string'},
                                            'urgency': {'type': 'string', 'enum': ['low', 'medium', 'high']},
                                            'source_ref': {'type': 'string',
                                                           'description': 'Repo-relative source path only. Use scope_refs for projects/... and session_refs for agent/thread ids.'},
                                            'suggested_context_sources': {'type': 'array', 'items': {'type': 'string'}},
                                            'client_request_id': {'type': 'string'},
                                            'startup_bundle_ref': {'type': 'string'},
                                            'packet_ref': {'type': 'string'},
                                            'handoff_ref': {'type': 'string'},
                                            'scope_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'session_refs': {'type': 'array', 'items': {'type': 'string'}},
                                            'artifact_refs': {'type': 'array', 'items': {'type': 'string'}}},
                             'required': ['scope',
                                          'proposed_project_id',
                                          'actor_role',
                                          'agent_family',
                                          'agent_instance_id',
                                          'work_type',
                                          'work_lane',
                                          'title',
                                          'summary',
                                          'reason']}}]
